export const carpets = [
  {
    id: 1,
    name: "Ковер с рисунком",
    image: "/images/carpet1.jpg",
    description: "Красивый ковер с современным рисунком.",
    price: 1500,
    stock: 10,
    category: "Ковры с рисунком",
  },
  {
    id: 2,
    name: "Ковер для гостиной",
    image: "/images/carpet2.jpg",
    description: "Элегантный ковер для гостиной комнаты.",
    price: 2500,
    stock: 5,
    category: "Гостиные ковры",
  },
  {
    id: 3,
    name: "Шерстяной ковер",
    image: "/images/carpet3.jpg",
    description: "Мягкий и уютный шерстяной ковер.",
    price: 3500,
    stock: 0,
    category: "Шерстяные ковры",
  },
  {
    id: 4,
    name: "Ковер в детскую",
    image: "/images/carpet4.jpg",
    description: "Яркий и безопасный ковер для детской комнаты.",
    price: 1200,
    stock: 8,
    category: "Детские ковры",
  },
  {
    id: 5,
    name: "Ковер с длинным ворсом",
    image: "/images/carpet5.jpg",
    description: "Комфортный ковер с длинным ворсом.",
    price: 4000,
    stock: 3,
    category: "Длинноворсовые ковры",
  },
];